name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.4'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install system librtlsdr
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y --no-install-recommends librtlsdr-dev

      - name: Rspec
        run: bundle exec rspec

  gem-build-test:
    runs-on: ubuntu-latest
    name: Gem Build and Installation Test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true

      - name: Install system librtlsdr
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y --no-install-recommends librtlsdr-dev

      - name: Check librtlsdr availability
        run: |
          bundle exec rake check_librtlsdr

      - name: Build and install gem locally
        run: |
          bundle install
          echo "Building gem..."
          gem build rtlsdr.gemspec --output rtlsdr.gem
          echo "Installing gem..."
          gem install ./rtlsdr.gem
          echo "Gem installed successfully"

      - name: Test gem functionality
        run: |
          ruby -e "
            require 'rtlsdr'
            puts 'Successfully loaded rtlsdr gem'
            puts 'RTLSDR::VERSION: ' + RTLSDR::VERSION
            puts 'Device count: ' + RTLSDR.device_count.to_s
            puts 'FFI library loading successful!'

            # Test that we can access device enumeration
            devices = RTLSDR.devices
            puts 'Available devices: ' + devices.length.to_s

            # Test FFI constants
            puts 'Tuner types available: E4000=' + RTLSDR::FFI::RTLSDR_TUNER_E4000.to_s
            puts 'All tests passed!'
          "
